# Generated by Django 3.2.3 on 2021-05-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='datecompleted',
        ),
    ]
